Fix `AttributeError: 'NoneType' object has no attribute 'cetoni_max_time_without_traffic'`
This error comes from the fact that a feature implementation is
decorated with `CetoniApplicationSystem.monitor_traffic` but there is no
`CetoniApplicationSystem` instance because the current application
configuration does not include CETONI devices. In this case we don't
want/need to monitor the traffic which is the new behavior now.